apiVersion: v1
kind: Namespace
metadata:
  name: mas-toolkit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mas-toolkit
  namespace: mas-toolkit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mas-toolkit-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mas-toolkit
    namespace: mas-toolkit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mas-toolkit-data
  namespace: mas-toolkit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-toolkit
  namespace: mas-toolkit
  labels:
    app: mas-toolkit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mas-toolkit
  template:
    metadata:
      labels:
        app: mas-toolkit
    spec:
      serviceAccountName: mas-toolkit
      containers:
        - name: mas-cli
          image: quay.io/ibmmas/cli:23.11.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-c","--"]
          args: ["while true; do sleep 30; done"]
          volumeMounts:
            - name: toolkit-data
              mountPath: /mascli
      volumes:
        - name: toolkit-data
          persistentVolumeClaim:
            claimName: mas-toolkit-data
